defaults: &defaults
  app_suffix: pricing
  org: TW-org
  is_service: true
  requires_postgres: true

test:
  <<: *defaults
  space: test

staging:
  <<: *defaults
  space: staging

production:
  <<: *defaults
  space: production
